import type { NextConfig } from "next";

const nextConfig: NextConfig = {
    eslint: {
    // IGNORE ESLINT ERRORS IN BUILD
    ignoreDuringBuilds: true,
  },
  env: {
    NEXT_PUBLIC_CANISTER_ID_INTERNET_IDENTITY: process.env.CANISTER_ID_INTERNET_IDENTITY,
    NEXT_PUBLIC_CANISTER_ID_KAI_BACKEND: process.env.CANISTER_ID_KAI_BACKEND,
    NEXT_PUBLIC_CANISTER_ID_TRACKS_BACKEND: process.env.CANISTER_ID_TRACKS_BACKEND,
    NEXT_PUBLIC_CANISTER_ID_CHATS_BACKEND: process.env.CANISTER_ID_CHATS_BACKEND,
    NEXT_PUBLIC_CANISTER_ID_NFT_CERTIFICATES: process.env.CANISTER_ID_NFT_CERTIFICATES,
    NEXT_PUBLIC_DFX_NETWORK: process.env.DFX_NETWORK
  }
};

export default nextConfig;
