import { Injectable } from '@nestjs/common';

@Injectable()
export class CertificateSvgFactory {
  create(owner: string, trackName: string, timeSpentHours: number): string {
    return `
<svg xmlns="http://www.w3.org/2000/svg" width="720" height="520" viewBox="0 0 720 520">
  <rect width="720" height="520" rx="28" fill="#101828"/>
  <rect x="18" y="18" width="684" height="484" rx="20" fill="#182230" stroke="#f59e0b" stroke-width="3"/>
  <text x="360" y="120" text-anchor="middle" fill="#f8fafc" font-size="36" font-family="Arial">Kaisen Certificate</text>
  <text x="360" y="200" text-anchor="middle" fill="#f59e0b" font-size="28" font-family="Arial">${owner}</text>
  <text x="360" y="250" text-anchor="middle" fill="#cbd5e1" font-size="22" font-family="Arial">completed ${trackName}</text>
  <text x="360" y="310" text-anchor="middle" fill="#94a3b8" font-size="18" font-family="Arial">Time spent: ${timeSpentHours} hours</text>
  <text x="360" y="400" text-anchor="middle" fill="#64748b" font-size="16" font-family="Arial">Generated by the NestJS backend</text>
</svg>`.trim();
  }
}
